# version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: tj_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: tj_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: tj_mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./docker/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  api:
    build: .
    container_name: tj_api
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "${API_PORT}:3000"
    command: ["/bin/api"]

  mqtt-subscriber:
    build: .
    container_name: tj_mqtt_subscriber
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_started
      mosquitto:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    command: ["/bin/mqtt-subscriber"]

  worker:
    build: .
    container_name: tj_worker
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: ["/bin/worker"]

volumes:
  pgdata:
